--- 
title: "Skeleton Tutorial Template"
author: "TJ McKinley"
site: bookdown::bookdown_site
output:
    bookdown::gitbook:
        config:
            sharing: null
        css: 'style.css'
        includes:
            in_header: _toggle.html
    bookdown::pdf_book:
        keep_tex: yes
        includes:
            in_header: header.tex
linkcolor: blue
documentclass: book
link-citations: yes
description: "Skeleton Tutorial Template"
---

# Opening page

```{r, child = "_setup.Rmd", include = F, purl = F, cache = F}
```

Basically a standard Bookdown template with a few tweaks. New chapters need to be in separate '.Rmd' files, where each file starts with a chapter heading as seen [here](https://bookdown.org/yihui/bookdown/usage.html). In order to use the task and solution blocks in \LaTeX, you must input the order of the files into the `_bookdown.yml` file, and the first file must be called `index.Rmd` e.g.

```
rmd_files:
    html: ['index.Rmd', 'ch1.Rmd']
    latex: ['index.Rmd', 'ch1.Rmd', 'ch_appendix.Rmd']
output_dir: "docs"
```

The `latex:` path above ***must*** have `'ch_appendix.Rmd'` as its last entry. This ensures that the appendix is properly formatted for the solutions to the problems.

There are a couple of useful special blocks. A `task` block, and a `solution` block. These can be used as e.g.

````
```{task}`r ''`
Here is a task written in **markdown**.
```
````

which renders as:

```{task}
Here is a task written in **markdown**.
```

You can include chunks within the `task` chunk, but you need to use double backticks *within* the chunk, and leave carriage returns around the internal chunk e.g.

````

```{task}`r ''`

``{r}
x <- 2 + 2
x
``

```

````

which renders as:

```{task}

``{r}
x <- 2 + 2
x
``

```

Be careful to have suitable carriage returns around e.g. `enumerate` or `itemize` environments inside the chunk also. For example:

````

```{task}`r ''`
Here is a list:
1. item 1
2. item 2
```

```` 

will not render nicely. But

````

```{task}`r ''`
Here is a list:

1. item 1
2. item 2

```

```` 

will:

```{task}
Here is a list:

1. item 1
2. item 2

```

The `solution` chunk works in the same way, and the numbers will follow the previous `task` chunk (so you can set tasks without solutions) e.g.

````

```{task}`r ''`
Add 2 and 2 together
```

```{solution}`r ''`

``{r}
2 + 2
``

```

````

gives:

```{task}
Add 2 and 2 together
```

```{solution}

``{r}
2 + 2
``

```

To compile, run the `_build.sh` script which will compile into multiple formats. 
